# Generated by Django 4.1.2 on 2024-10-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
